### ISSUE TITLE
run-command fails with error no such file error

### ISSUE THREAD

**Issue by AkashJohnSubash** [matlab-actions/setup-matlab#108]
To use the cache feature, I updated my workflow to use setup-matlab@v2 from setup-matlab@v1
However, with v2 the [Run Simulink Test](https://github.com/AkashJohnSubash/acados/actions/runs/8833092685/job/24251757963) fails since simstruc.h cannot be found.

**Comment by davidbuzinski** [comment]
Hi @AkashJohnSubash ,

setup-matlab@v2 now requires specifying the [products ](https://github.com/matlab-actions/setup-matlab?tab=readme-ov-file#set-up-matlab)that the builds requires beyond MATLAB.

You may need to update your CI .yml file to specify the products required. The products parameter takes a space-separated list of products. Spaces in the product names should be replaced with underscores (see the [README ](https://github.com/matlab-actions/setup-matlab?tab=readme-ov-file#set-up-matlab) for a full explanation and examples). Here is an example that includes Simulink and Simulink Test:
```
    - name: Setup MATLAB
      uses: matlab-actions/setup-matlab@v2
      with:
        products: Simulink Simulink_Test
```
