### ISSUE TITLE
Request R2024b prerelease

### ISSUE THREAD

**Issue by scivision** [matlab-actions/setup-matlab#117]
Requesting option for R2024b prerelease.

**Comment by davidbuzinski** [comment]
Hi @scivision ,

We currently provide undocumented support for prerelease using the `latest-including-prerelease` keyword. This keyword will flip to 24b GR when it is released at the same time that the `latest` release keyword switches over. It should always be our latest release which could either be a GR or a prerelease.

Please note that this API is currently undocumented and subject to change, but I will keep this issue open, and close it when we document it, or update it if the API changes.

Here is some sample yaml that should work to install the 24b prerelease using our actions:
```
on: [push]
jobs: 
  my-job:
    name: Run Build
    runs-on: ubuntu-24.04
    steps: 
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: latest-including-prerelease
      - name: Run command
        uses: matlab-actions/run-command@v2
        with:
          command: ver
```
