### ISSUE TITLE
Calling setup-matlab twice in a single workflow causes an error

### ISSUE THREAD

**Issue by mcafaro** [matlab-actions/setup-matlab#130]
If you attempt to call `setup-matlab` twice in a single workflow, to set up two different releases of MATLAB for instance, the second call will result in an error saying "Destination file path /home/runner/work/_temp/mpm already exists".

Reproduction workflow:
```yaml
name: MATLAB
on: [push]
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Set up MATLAB R2024b
        uses: matlab-actions/setup-matlab@v2
        with:
          release: R2024b

      - name: Set up MATLAB R2024a
        uses: matlab-actions/setup-matlab@v2
        with:
          release: R2024a
```

Error:
<img width="686" alt="Image" src="https://github.com/user-attachments/assets/0c54811e-75a0-41d2-b8ce-ecf31989bfc8" />
