### ISSUE TITLE
'parpool(2)' fails

### ISSUE THREAD

**Issue by OptHuang** [matlab-actions/setup-matlab#131]
Strange bug occurs when I am testing `parpool(2)` on MATLAB R2021b, R2022a, and R2022b as follows.

*************
Error using parpool 
  Undefined function 'pCurrentTaskIsPartOfAPool' for input arguments of type 
  'double'. 
  
  Error in solveAllProblems (line 68) 
                  parpool(numJobs);
*************

Reproduction workflow:

```
name: test parallel computing toolbox

on:
  push:
    branches: [matlab]

jobs:

  test:

    name: MATLAB ${{ matrix.matlab }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        matlab: [latest, R2021b, R2022a, R2022b, R2023a, R2023b]

    steps:

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up MATLAB with optimization toolbox and parallel computing toolbox
        uses: matlab-actions/setup-matlab@v2
        with:
          release: ${{ matrix.matlab }}
          cache: true
          products: Optimization_Toolbox Parallel_Computing_Toolbox

      - name: Test parallel computing
        uses: matlab-actions/run-command@v2.1.1
        with:
          command: |
            parpool(2)
```
