### ISSUE TITLE
setup-matlab fails

### ISSUE THREAD

**Issue by ehennestad** [matlab-actions/setup-matlab#146]
I am currently getting this error:

```
Setting up MATLAB
  /usr/bin/chmod +x /home/runner/work/_temp/mpm
  /home/runner/work/_temp/mpm install --release=r2024b --destination=/opt/hostedtoolcache/MATLAB/2024.2.999/x64 --products MATLAB
  Installing with the following parameters:
  --destination=/opt/hostedtoolcache/MATLAB/2024.2.999/x64
  --release=R2024b
  --products=MATLAB
  ---------------------------------------------
  Error: mpm version 2025.1 is not supported. Download the latest version of mpm.
Error: Error: The process '/home/runner/work/_temp/mpm' failed with exit code 255

```

Using the following step in a GitHub Actions workflow:

```yaml
      - name: Set up MATLAB (${{ inputs.matlab_release }})
        uses: matlab-actions/setup-matlab@v2
        with:
          release: ${{ inputs.matlab_release }}
```

where inputs.matlab_release is "latest"
