### ISSUE TITLE
Cannot build MATLAB Engine for Python

### ISSUE THREAD

**Issue by SNDST00M** [matlab-actions/setup-matlab#22]
It appears I am trying to "build a wheel from code stored in a mounted storage account".
I'd be making a temp directory, copy things over and that would get the build working:
https://stackoverflow.com/questions/63243930/

I do not know what I am doing at this point, but here is my YML:
https://github.com/apommel/vscode-matlab-interactive-terminal/blob/84219db/.github/workflows/ci.yml

Maybe there needs to be an action for building MATLAB Engine for Python that handles the VM issue?

**Comment by acampbel** [comment]
hi there, thanks for trying these actions. Yu may be able to build the engine by [building and installing in non-default locations](https://www.mathworks.com/help/matlab/matlab_external/install-matlab-engine-api-for-python-in-nondefault-locations.html).

However, even if you can build and install it you may run into  licensing issue similar to [this issue](https://github.com/matlab-actions/setup-matlab/issues/13) when you try to run the engine. DO you find yourself in the same situation?

**Comment by mcafaro** [comment]
You can workaround this issue by specifying the `--build-base` option as shown:

```yaml
    - name: Install MATLAB Engine for Python
      run: |
        cd /usr/local/MATLAB/R2021a/extern/engines/python
        python setup.py build --build-base=$(mktemp -d) install --user
```

Note that you will not be able to call `matlab.engine.start_matlab()` however (it will fail with a licensing error) as our cloud based licensing currently occurs upon MATLAB startup and the MATLAB engine for Python does not yet support this licensing scheme.
