### ISSUE TITLE
How to specify MATLAB release

### ISSUE THREAD

**Issue by Isaac-Ito-MW** [matlab-actions/setup-matlab#28]
Hi, I'd like to specify MATLAB release in setup-matlab. The README says that the action accepts the "release" option for that, but how can I specifically set it in ci.yml file?

**Comment by mcafaro** [comment]
Hi @Isaac-Ito-MW,

You can specify the release as follow:

```yaml
- name: Set up MATLAB
  uses: matlab-actions/setup-matlab@v1
  with:
    release: R2021a
```

Please note the specified release must be R2020a or later.

Best,
Mark
