### ISSUE TITLE
GitHub Actions deprecation warning

### ISSUE THREAD

**Issue by scivision** [matlab-actions/setup-matlab#46]
This warning occurs for the setup-matlab action:

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: matlab-actions/setup-matlab, matlab-actions/run-command

I'm not familiar with the internals of matlab-actions, but possibly under .github/workflows updating to the following would help:

```yml
- uses: actions/setup-node@v3
  with:
    node-version: 16
```
