### ISSUE TITLE
Workflows crash with a segmentation violation after `matlab-actions/setup-matlab@v1.2.4` finishes and before `matlab-actions/run-command@v1.1.3` starts

### ISSUE THREAD

**Issue by zaikunzhang** [matlab-actions/setup-matlab#59]
Recently, it has been happening from time to time (but not always) that my workflows crash with a segmentation violation right after `matlab-actions/setup-matlab@v1.2.4` finishes and before `matlab-actions/run-command@v1.1.3` starts. 

Here are two examples: 

[crash1.log](https://github.com/matlab-actions/setup-matlab/files/10949761/crash1.log)
[workflow1](https://github.com/libprima/prima/blob/main/.github/workflows/verify_small.yml)

[crash2.log](https://github.com/matlab-actions/setup-matlab/files/10949762/crash2.log)
[workflow2](https://github.com/libprima/prima/blob/main/.github/workflows/profile_lincoa_small.yml)

Since the crash happens randomly, I do not expect it will be trivial to debug. But it will still be great if you could have a look.

Thanks.

**Comment by mcafaro** [comment]
Can you give `matlab-actions/setup-matlab@v2-beta` a try? It may increase the time required to set up MATLAB (particularly with older releases) but it may also help address this crash.

**Note:** with setup-matlab v2, you need to explicitly specify the products required for your build with the `products` input like so:

```yaml
- name: Install MATLAB
  uses: matlab-actions/setup-matlab@v2-beta
  with:
    release: latest
    products: |
      Simulink
      Deep_Learning_Toolbox
```

See the [v2 README](https://github.com/matlab-actions/setup-matlab/tree/v2-beta#set-up-matlab) for more details.
