### ISSUE TITLE
Choose the root directory of MATLAB

### ISSUE THREAD

**Issue by zaikunzhang** [matlab-actions/setup-matlab#62]
Is it possible to provide an option that supports a user-defined root directory of MATLAB?

In my project, I would like to modify the xml files under 'mexopts', which is read only. In addition, GitHub actions do not support chmod.

Thank you for your consideration.

**Comment by mcafaro** [comment]
You can modify the MATLAB root with `setup-matlab@v2-beta`, as shown:

```yaml
name: Run MATLAB Build on GitHub-Hosted Runner
on: [push]
jobs:
  my-job:
    name: Run MATLAB Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up MATLAB
        id: set-up-matlab
        uses: matlab-actions/setup-matlab@v2-beta
      - name: Add file to mexopts folder
        run: touch ${{steps.set-up-matlab.outputs.matlabroot}}/bin/glnxa64/mexopts/my_mexopts.xml
      - name: List files in mexopts folder
        run: ls ${{steps.set-up-matlab.outputs.matlabroot}}/bin/glnxa64/mexopts
```

Because of the way `setup-matlab@v1` works, it is not possible to modify the MATLAB root folder even if we support specifying a user-defined location.
